version: '2.4'

services:
    nginx:
        extends:
            file: .docker/nginx/nginx-compose.yml
            service: nginx
        restart: unless-stopped
        depends_on:
            - fpm
        links:
            - fpm:php
        volumes:
            - .:/app
        ports:
            - 8010:80

    fpm:
        extends:
            file: .docker/php/php-compose.yml
            service: php
        restart: unless-stopped
        depends_on:
            - db
        volumes:
            - .:/app
        environment:
            - XDEBUG_PORT=9103
    #    user: 1000:1000

    queue:
        extends:
            file: .docker/php/php-compose.yml
            service: php
        restart: unless-stopped
        command: php artisan queue:work --tries=3
        depends_on:
            - db
        volumes:
            - .:/app

    composer:
        extends:
            file: .docker/php/php-compose.yml
            service: composer
        depends_on:
            - db
        volumes:
            - .:/app

    db:
        extends:
            file: .docker/postgres/postgres-compose.yml
            service: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - ${POSTGRES_PORT}:5432
    #ports: #if you want to use db manager instead console
    # - 5439:5433

    testdb:
        extends:
            file: .docker/postgres/postgres-compose.yml
            service: test
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
            - "15672:15672"
